Repository yoonwooiOS/PocketTheater, pull requests merged in 2024-10, with the labels that each got.

#4 Feat: TabBarController 구현, 홈/검색/좋아요 화면 연결
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Application/SceneDelegate.swift
  PocketTheater/Component/Base/BaseViewController.swift
  PocketTheater/Presentation/Home/HomeView.swift
  PocketTheater/Presentation/Home/HomeViewController.swift
  PocketTheater/Presentation/Like/LikeView.swift
  PocketTheater/Presentation/Like/LikeViewController.swift
  PocketTheater/Presentation/Search/SearchView.swift
  PocketTheater/Presentation/Search/SearchViewController.swift
  PocketTheater/Presentation/TabBar/HomeTabBarController.swift
  PocketTheater/Resource/Resource.swift
Labels: 기능, 완료, 디자인

#5 Feat: TabBarController 구현, 홈/검색/좋아요 화면 연결 (To 'dev' branch)
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Application/SceneDelegate.swift
  PocketTheater/Component/Base/BaseViewController.swift
  PocketTheater/Presentation/Home/HomeView.swift
  PocketTheater/Presentation/Home/HomeViewController.swift
  PocketTheater/Presentation/Like/LikeView.swift
  PocketTheater/Presentation/Like/LikeViewController.swift
  PocketTheater/Presentation/Search/SearchView.swift
  PocketTheater/Presentation/Search/SearchViewController.swift
  PocketTheater/Presentation/TabBar/HomeTabBarController.swift
  PocketTheater/Resource/Resource.swift
Labels: 기능, 완료, 디자인

#9 Chore: Realm DB Table 설계 (좋아요 기능)
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Database/LikeTable.swift
Labels: 완료, 기타

#10 Feat: NetworkManager 구성, Model 추가
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Database/LikeTable.swift
  PocketTheater/Model/Cast.swift
  PocketTheater/Model/Genre.swift
  PocketTheater/Model/Media.swift
  PocketTheater/Network/NetworkManager.swift
  PocketTheater/Presentation/TabBar/HomeTabBarController.swift
Labels: 기능, 완료

#15 Refactor: NetworkManager에 fetchImage수정하며 관련 함수 수정 및 추가
  PocketTheater/Network/NetworkManager.swift
Labels: 기능, 완료

#18 Design: 미디어 상세 화면 구현
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Component/Base/BaseCollectionViewCell.swift
  PocketTheater/Component/CollectionViewCell/MediaCollectionViewCell.swift
  PocketTheater/Component/CustomView/ActionButton.swift
  PocketTheater/Database/LikeRepository.swift
  PocketTheater/Presentation/Detail/DetailHeaderView.swift
  PocketTheater/Presentation/Detail/DetailView.swift
  PocketTheater/Presentation/Detail/DetailViewController.swift
  PocketTheater/Presentation/Detail/DetailViewModel.swift
  PocketTheater/Presentation/Like/LikeView.swift
  PocketTheater/Presentation/Like/LikeViewController.swift
  PocketTheater/Presentation/Play/PlayView.swift
  PocketTheater/Presentation/Play/PlayViewController.swift
  PocketTheater/Presentation/TabBar/HomeTabBarController.swift
  PocketTheater/Resource/Resource.swift
Labels: 완료, 디자인

#20 Feat: MediaPlayCollectionViewCell, createMediaPlayCellLayout 메서드 추가
  PocketTheater/Component/CollectionViewCell/MediaPlayCollectionViewCell.swift
  PocketTheater/Resource/Resource.swift
Labels: 완료, 디자인

#21 Chore: pbxproject 추가
  PocketTheater.xcodeproj/project.pbxproj
Labels: 완료, 기타

#23 Design: 좋아요 탭 화면 RxDatasource 기본 코드 구성
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Database/LikeRepository.swift
  PocketTheater/Presentation/Detail/DetailViewController.swift
  PocketTheater/Presentation/Like/LikeView.swift
  PocketTheater/Presentation/Like/LikeViewController.swift
  PocketTheater/Presentation/Like/LikeViewModel.swift
  PocketTheater/Resource/Constant.swift
  PocketTheater/Resource/Resource.swift
Labels: 완료, 디자인

#25 Feat: SearchView 구현
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Component/CollectionViewCell/MediaCollectionViewCell.swift
  PocketTheater/Component/CollectionViewCell/MediaPlayCollectionViewCell.swift
  PocketTheater/Network/NetworkManager.swift
  PocketTheater/Presentation/Search/NoSearchResultCell.swift
  PocketTheater/Presentation/Search/SearchMediaSection.swift
  PocketTheater/Presentation/Search/SearchMediaSectionHeaderView.swift
  PocketTheater/Presentation/Search/SearchView.swift
  PocketTheater/Presentation/Search/SearchViewController.swift
  PocketTheater/Presentation/Search/SearchViewModel.swift
  PocketTheater/Presentation/TabBar/HomeTabBarController.swift
Labels: 기능, 완료, 디자인

#26 Fix: Search API 통신 모델 변경
  PocketTheater/Component/CollectionViewCell/MediaCollectionViewCell.swift
  PocketTheater/Component/CollectionViewCell/MediaPlayCollectionViewCell.swift
  PocketTheater/Presentation/Search/SearchMediaSection.swift
  PocketTheater/Presentation/Search/SearchViewModel.swift
Labels: 기능

#28 Feat: Home화면 구현
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Application/Assets.xcassets/Netflix_Symbol_RGB.imageset/Contents.json
  PocketTheater/Application/Assets.xcassets/Netflix_Symbol_RGB.imageset/Netflix_Symbol_RGB.png
  PocketTheater/Component/Base/BaseViewController.swift
  PocketTheater/Component/CollectionViewCell/MediaCollectionViewCell.swift
  PocketTheater/Component/CustomView/ActionButton.swift
  PocketTheater/Network/NetworkManager.swift
  PocketTheater/Presentation/Home/FeaturedCollectionViewCell.swift
  PocketTheater/Presentation/Home/HomeCollectionViewCell.swift
  PocketTheater/Presentation/Home/HomeView.swift
  PocketTheater/Presentation/Home/HomeViewController.swift
  PocketTheater/Presentation/Home/HomeViewModel.swift
  PocketTheater/Presentation/Like/LikeView.swift
  PocketTheater/Presentation/Search/SearchMediaSection.swift
  PocketTheater/Presentation/Search/SearchMediaSectionHeaderView.swift
  PocketTheater/Presentation/Search/SearchViewController.swift
  PocketTheater/Presentation/Search/SearchViewModel.swift
  PocketTheater/Presentation/TabBar/HomeTabBarController.swift
Labels: 기능, 완료, 디자인

#30 Feat: 내가 찜한 리스트 버튼 구현 완료
  PocketTheater.xcodeproj/project.pbxproj
  PocketTheater/Component/CustomView/CustomAlertView.swift
  PocketTheater/Database/LikeRepository.swift
  PocketTheater/Extension/UIViewController+Extension.swift
  PocketTheater/Presentation/Home/HomeViewController.swift
Labels: 기능

#32 Feat: like 구현 완료
  PocketTheater/Component/CollectionViewCell/MediaPlayTableViewCell.swift
  PocketTheater/Database/LikeRepository.swift
  PocketTheater/Presentation/Like/LikeViewController.swift
  PocketTheater/Presentation/Like/LikeViewModel.swift
Labels: 기능, 완료

#34 WIP: 충돌 오류 확인
  PocketTheater/Network/NetworkManager.swift
  PocketTheater/Presentation/Detail/DetailHeaderView.swift
  PocketTheater/Presentation/Detail/DetailView.swift
  PocketTheater/Presentation/Play/PlayView.swift
  PocketTheater/Presentation/Play/PlayViewController.swift
  PocketTheater/Presentation/Search/SearchMediaSection.swift
  PocketTheater/Presentation/Search/SearchViewController.swift
  PocketTheater/Presentation/Search/SearchViewModel.swift
Labels: 진행 중
